name: gridding-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - xarray
  - dask
  - netcdf4
  - zarr
  - pyresample
  - cartopy
  - appdirs
  - verde
  - xesmf>=0.7
  - seaborn
  - sphinx-pythia-theme
  - pip
  - pip:
      - watermark
